name: dl-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - tensorflow-gpu=1.13
  - h5py=2.10.0
  - jupyter
  - numpy<1.17.0
  - matplotlib
  - mlflow=1.7.0
  - seaborn
  - pandas
  - scikit-learn=0.22.1
  - opencv=4.2.0
  - keras-gpu=2.3.1
  - pillow
  - pydot
  - shap=0.35.0
  - scipy=1.1.0
  - imbalanced-learn=0.6.2
  - pip:
    - scikit-multilearn==0.2.0
