name: dl-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu==1.13.1
  - keras-gpu==2.3.1
  - ipython
  - jupyter
  - opencv==4.2
  - matplotlib
  - scikit-learn=0.22.1
  - h5py==2.10.0
  - seaborn
  - mlflow
  - numpy[version='<1.17']
