name: icaonet
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.10
  - keras-gpu==2.3.1
  - ipython
  - jupyter
  - opencv==4.2
  - matplotlib
  - scikit-learn=0.22.1
  - h5py==2.10.0
  - seaborn
  - mlflow==1.11.0
  - numpy[version='<1.17']
  - imbalanced-learn=0.6.2
  - pip:
    - scikit-multilearn==0.2.0
    - tensorflow-gpu==1.13.1
